version: '3.7'
services:
  webserver:
    image: vaccine-webserver
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-webserver
    ports:
      - 8000:8000
    volumes:
      #load local code and aws environment for development
      - "./:/app"
    command: bash /logout4shell/start_webserver.sh

  ldapserver:
    image: vaccine-ldapserver
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-ldapserver
    command: bash /ldapserver/start_ldapserver.sh
    ports:
      - 1389:1389
    depends_on:
      - webserver
    env_file:
      - containers.env
